### ISSUE TITLE
Get phrases from ASS/SRT subtitles

### ISSUE THREAD

**Issue by devdouglasonofre** [sheodox/japanese-context-sentence-review#45]
**Improvement suggestion**
Extract text from ASS/SRT subtitles.

Why?
For Poem/Novel/Song Lyrics, the phrase extraction works like a charm. But in the case of subtitles files, copying text from there may be cumbersome and time consuming. Having a automated subtitle to CR phrase will save a lot of time.

Use case:
I want to mine the vocabulary of an anime/drama/movie straight from the subtitles.

**Comment by devdouglasonofre** [comment]
[This library](https://github.com/XiangnianZhou/neta) may be useful.

**Comment by sheodox** [comment]
I actually have another project that deals with subtitles called Jimaku Player and I've written my own parser and renderer for ASS and SRT https://github.com/sheodox/jimaku-player

I'm not sure what you use to watch anime, but if you use VRV or Crunchyroll you could use that and watch anime there with your SRT/ASS file. If you click on a subtitle it will search it on Jisho so you could use that to get your subtitles into CR. I had planned on building in better integration which skips Jisho and just adds it right to CR.

I do like the idea of supporting importing phrases from subtitles or something directly though. I'll think about it.

**Comment by devdouglasonofre** [comment]
Just tested the Jimaku and works wonderfully. It's like the Anacreon, but without the need to have 3 things open to start mining. Great tool.

There is a way to get the **entire** subtitles for said episode in the Jimaku without having to watch the entire episode? I mean, I want to mine it _before_ watching, so with the entire subtitles parsed to plain text, I would just paste in the CR and starting mining from there.

**Comment by devdouglasonofre** [comment]
By the way, another suggestion: a button to delete all phrases without having to export to Anki.

**Comment by sheodox** [comment]
Yeah the subtitle thing is a great idea. I'll put it on my todo list.

> By the way, another suggestion: a button to delete all phrases without having to export to Anki.

I actually have that already, but it's kind of hidden. If you click your profile picture in the top right corner and go to Settings, then the Stats tab, there's a delete all button! I'll probably put that in a more obvious place somewhere.

![image](https://user-images.githubusercontent.com/3468630/153950712-293e7963-def7-4647-9f46-a5fec6e683a2.png)

**Comment by devdouglasonofre** [comment]
Thanks for pointing out!

**Comment by sheodox** [comment]
@devdouglasonofre I just deployed an update that adds this functionality, try it out!!

![image](https://user-images.githubusercontent.com/3468630/154277079-e66ee8de-2a0a-4e8b-b3f5-ef6b3772d184.png)

Now when you're viewing the phrase list there's a `+ Import Phrases` button that will let you choose either plain text or subtitles. If you choose subtitles you can upload a `.srt`/`.vtt`/`.ass`/`.ssa` file and it will give you a list of all the subtitles in there and you can pick what you want to add.

![image](https://user-images.githubusercontent.com/3468630/154277043-059f43dc-78ff-4501-9e02-f9f3ec45a0ab.png)

I also moved both of those buttons from the Stats page to a '...' button on the phrase list's toolbar.
![image](https://user-images.githubusercontent.com/3468630/154276965-2bd2aa04-cf51-473a-8884-05a9d2fe4e94.png)

**Comment by devdouglasonofre** [comment]
Amazing work! Tested with an SRT file and worked like a charm!

However, when I tried with an .ass:
![image](https://user-images.githubusercontent.com/43081345/154319116-0256618e-b617-4e42-897d-b44c70e389d2.png)

This is the .ass file that I was trying to import:
[grisaia kaijutsu 1.txt](https://github.com/sheodox/context.reviews/files/8081963/grisaia.kaijutsu.1.txt)
(Converted to txt because GitHub don't allow the upload of .ass files. But the content is the same)

**Comment by sheodox** [comment]
Hey good catch! That subtitle file has an extra blank line in amongst the subtitles and my parser got confused. I fixed it now though so it should be able to handle that!`

**Comment by devdouglasonofre** [comment]
Working perfectly now! Thanks a lot for you hard work!

**Comment by sheodox** [comment]
Nice!! You're welcome, and thanks to you too for the good ideas!
